#  psql -h localhost -p 5432 -d dev -U dev

version: "3.9"
services:
  postgres:
    image: "postgres"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_DB: "dev"
volumes:
  postgresql-data:
